services:

  gomoku-core-api:
    build:
      context: ./gomoku-core-api
      dockerfile: Dockerfile
    container_name: gomoku-core-api
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gomoku-web-ang:
    build:
      context: ./gomoku-web-ang
    container_name: gomoku-web-ang
    ports:
      - "4200:4200"
    volumes:
      - ./gomoku-web-ang:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"