export enum GameEventTypeEnum {
	GAME_UPDATED = 'GAME_UPDATED',
	PLAYER_JOINED = 'PLAYER_JOINED',
	VISIBILITY_CHANGED = 'VISIBILITY_CHANGED',
	GAME_STARTED = 'GAME_STARTED',
	TURN_PLAYED = 'TURN_PLAYED',
}
